### ISSUE TITLE
Definition of `unregistered`

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#127]
In `DiscoverFromExternalSource` step 11, is it correct to state that `unregistered` means this IDP account has not previously used Credential Management to sign-in to the given RP?

(The distinction of Credential Management because the user may have signed into the RP previously using a 3rd party cookie method with the given IDP account)

**Comment by samuelgoto** [comment]
> In `DiscoverFromExternalSource` step 11, is it correct to state that unregistered means this IDP account has not previously used Credential Management to sign-in to the given RP?

Yes. 

It means "does my user agent know that I have registered an account at the RP with the IDP?", which is a different bit compared to "does my IDP know that I have registered an account at the RP". 

I think `unregistered means this IDP account has not previously used Credential Management` captures that distinction precisely.

> Is the Account State expected to be sync'd over devices?

Yes.

Notably, though, the awkward part here happens when a user moves **across** user agents. There is a bit in the `acounts_endpoint` that can tell the user agent "hey, if you have never seem this user at this RP, that's fine, go and ask for persmission/consent, but understand that the user already has an account there that was created out of band".

Does that make sense?

**Comment by dj2** [comment]
How does `accounts_endpoint` know an account exists? When we call `accounts_endpoint` there is no Referrer sent, as we don't want the IDP to know which RP the user is currently on, we just want the list of accounts for the IDP. We can't ask the RP as we don't want them to know the user has communicated with the IDP.

So, how does the IDP signal the user has an account on RP?

**Comment by asr-enid** [comment]
>> Is the Account State expected to be sync'd over devices?

>Yes.

For clarity - this assumes that the state machine is synchronised between user agents of the same type, in case the user enabled a general synching mechanism (that relies on a user agent proprietary login usually). Otherwise (no synch) we'd also get awkward parts unless there is a way to communicate this information IDP->UA

**Comment by samuelgoto** [comment]
> So, how does the IDP signal the user has an account on RP?

The proposal right now is for the IDP to send us a list of RPs (that the user has an account on) per account.

**Comment by samuelgoto** [comment]
> For clarity - this assumes that the state machine is synchronised between user agents of the same type, in case the user enabled a general synching mechanism (that relies on a user agent proprietary login usually). Otherwise (no synch) we'd also get awkward parts unless there is a way to communicate this information IDP->UA

That's a correct assumption.

**Comment by asr-enid** [comment]
>>So, how does the IDP signal the user has an account on RP?

>The proposal right now is for the IDP to send us a list of RPs (that the user has an account on) per account.

Okay - sharing a list avoids exposing the RP at this stage

**Comment by samuelgoto** [comment]
> Okay - sharing a list avoids exposing the RP at this stage

Right, that's the goal.

**Comment by dj2** [comment]
> > So, how does the IDP signal the user has an account on RP?
> 
> The proposal right now is for the IDP to send us a list of RPs (that the user has an account on) per account.

That seems like it could be excessively long if the user has logged into a lot of RPs. I wonder what the average number of RPs is for a user to sign into with a single IDP.

**Comment by samuelgoto** [comment]
> That seems like it could be excessively long if the user has logged into a lot of RPs. I wonder what the average number of RPs is for a user to sign into with a single IDP.

I think this should be a fairly smaller number, say < 1K. Bloom filters can make this smaller too if needed.

**Comment by dj2** [comment]
Bloomfilters have potential false positives, yea? Will be something to keep in mind if this is a considered route.
