### ISSUE TITLE
We should clarify how the RP acquires account id for use in hint field

### ISSUE THREAD

**Issue by pkotwicz** [fedidcg/FedCM#143]
- Does the RP use the id token / an access token to request the "account id" from the IDP?
- Does the navigator.credentials.get() JavaScript API return the user-selected "account id" in addition to the "id token"?

**Comment by dj2** [comment]
The spec isn't fully up to date yet. We currently have `navigator.credentials.get()` returning an `idToken` which doesn't really match how the Credentials Management works. It should instead return a `credentials` object which is a `FederatedCredential`. That `FederatedCredential` has an account_id in it. The RP could also have gotten it in some other fashion.

Instead of `get` returning the `idToken`, there should instead be a `fetchToken` API which returns the token. I'm looking to update this next week.

**Comment by dj2** [comment]
Changing this to be the ID used in the `hint`. The `revoke` endpoint no-longer takes a specific account_id but will get it through the `hint`.

**Comment by tanzachary** [comment]
When `disconnect` (previously revoke) is called, there must have been interaction between the RP and the IDP before. RP has information from before and the IDP lets the RP know what they need to revoke their credential, so they can communicate and revoke it for the correct user. Closing for now.
