### ISSUE TITLE
Hide RP's identity from IdP in Authentication

### ISSUE THREAD

**Issue by gtrs** [fedidcg/FedCM#27]
The current WebID proposal only hides at which RP a user is logging in from the IdP until the user gives consent to log in using the selected IdP. In particular, the attack scenario sketched in IDP1 is not mititgated (IdP tracks where a user signs-in). This proposal only addresses a slightly different attack scenario, i.e., that any IdP can always track where a user is about to log in.

One possiblity to address problem IDP1 can be similar to the solution that we propose in the SPRESSO SSO protocol. In this protocol, the IdP receives an encrypted string (which we call the _tag_). The tag contains a nonce and an identifier for the RP. The identifier of the RP, however, we mainly needed to work around browser restrictions. As WebID is probably not subject to such restrictions, it might be even sufficient to just use a plain nonce instead, i.e., just run a challenge/response between RP and IdP.

See https://www.sec.uni-stuttgart.de/research/wim/ for information on the protocol design of SPRESSO. In our research, we also analyzed several other SSO protocols (including BrowserID). You can find our results on this page as well.

**Comment by davidben** [comment]
Thanks for the pointer! Does SPRESSO allow for directed identifiers? That is, RP1 and RP2 get handed RP-specific identifiers (e.g. a forwarding email) so that this doesn't become a join key? Skimming the paper, it looks like the user identifiers are still the global ones.

I think the interaction between directed identifiers and IDP1 is the main challenge. Without directed identifiers, RP1 and RP2 (and any scripts they choose to embed) have a correlator for cross-site tracking. But directed identifiers mean *something* in the auth flow needs to look up a consistent identifier by RP. Additionally, RPs typically rely on both a consistent identifier *and* some communication ability (e.g. email address), so something needs to be able to reverse the mapping to deliver messages sent to this RP-specific communication handle.

**Comment by kenrb** [comment]
There are other challenges to RP hiding. In particular, there are IdP use cases that require them to know the OAuth client ID in the transaction, such as users wanting to revoke credentials from the IdP. BrowserID and SPRESSO are certainly interesting but they do require re-envisioning a lot about how federated identity works today.

As @davidben explains, though, the more fundamental challenge is the apparent conflict between [RP hiding](https://github.com/WICG/WebID/blob/master/privacy_threat_model.md#hiding-the-rp-from-the-idp) and [directed identifiers](https://github.com/WICG/WebID/blob/master/privacy_threat_model.md#directed-identifiers). So far I haven't seen any schemes that would allow us to have both.

**Comment by surfnet-niels** [comment]
Another issue with RP hiding is that for an IdP to release personal data during the The Provisioning Stage it needs to able to assess where the data is going. 
Several factors may determine the willingness of an IdP to release data like: 
- EU vs non-EU based RP (e.g. for GDPR compliance)
- Licensed content vs freely accessible (Do I as an IdP run the risk of getting a bill?)
- Brand association: User may interpret the ability to login using the IdP as a form of sanctioning of the RP by the IdP. However IdPs may not want their brand to be associated with all RPs (e.g. academic IdP providing login to gambling/porn)
All of the above are risks which will be assessed by an IdP *before* deciding to release data to an RP. Requiring IdP to release personal data into a 'black hole' because the target is not revealed will make such risk assessment impossible and hence release of PI  will be challenging.

**Comment by davidben** [comment]
The provisioning stage isn't about releasing data to the RP, just providing the UA with any RP-independent information that may be needed to display the initial browser-level consent prompt. (One could even imagine something analogous to the Payment Handler API, which has the payment provider [register a set of instruments](https://www.w3.org/TR/payment-handler/#dom-paymentmanager) with the browser.)

Such a split would still allow the IdP to take the RP into consideration once the browser is okay releasing that information to the IdP. The IdP is ultimately the one minting the IdToken.

**Comment by samuelgoto** [comment]
I think this makes general perfect sense. 

> BrowserID and SPRESSO are certainly interesting but they do require re-envisioning a lot about how federated identity works today.

I think re-envisioning is perfectly fine.

> In this protocol, the IdP receives an encrypted string (which we call the tag). The tag contains a nonce and an identifier for the RP.

This is a similar mechanism that describe here in the [delegation-oriented variation](https://docs.google.com/presentation/d/1Sym0k84omyL5Ls1lO6w4aGQ-s4EHrDzo8ZlheyzFOlw/edit#slide=id.ga40b1e6d4f_0_77). 

@gtrs any chance we can arrange a call for you to walk us through SPRESSO and compare and contrast approaches?

**Comment by gtrs** [comment]
> @gtrs any chance we can arrange a call for you to walk us through SPRESSO and compare and contrast approaches?

Sorry for the delay. Sure, I am happy to give you a walkthrough. Until Easter I am pretty busy. Maybe we can schedule a meeting after that?

**Comment by samuelgoto** [comment]
> The current WebID proposal only hides at which RP a user is logging in from the IdP until the user gives consent to log in using the selected IdP. In particular, the attack scenario sketched in IDP1 is not mititgated (IdP tracks where a user signs-in). This proposal only addresses a slightly different attack scenario, i.e., that any IdP can always track where a user is about to log in.

Just to report back on this thread: we wrote down in more details how we think we may want to go about solving this problem [here](https://docs.google.com/document/d/1ZymcC2ABSzwJloXje5R_KFLi0-Vaz03iLR9DjwQl9u0/edit). It is still early, but that's the best place to have that discussion.

**Comment by samuelgoto** [comment]
We are actively working on this problem at the Digital Credentials API, which solve this problem by breaking the IdP into a holder and an issuer.

https://github.com/WICG/digital-identities

I'm going to mark this as closed, since we were constrained by backwards compatibility, and allow the Digital Credentials API to address this issue.

Feel free to re-open if you feel like there is something in FedCM, specifically, that we could address.
