### ISSUE TITLE
[Technical] Icon sizes vs square / rectangular icons

### ISSUE THREAD

**Issue by nsatragno** [fedidcg/FedCM#302]
The specification says about icons:

```
url (required)
The url pointing to the icon image. The icon needs to comply with the [maskable](https://www.w3.org/TR/appmanifest/#icon-masks) specification.

size (optional)
The size of the icon. The icon is assumed to be square and single resolution (not a multi-resolution .ico). The size may be omitted if the icon is in a vector graphic format (like SVG).
```

And then in the example

```
    "icons": [{
      "url": "https://idp.example/icon.ico",
      "size": 10
    }]
```

If the size is going to be a single number, then perhaps saying the icons MUST / SHOULD be square is better. I'm not sure what the browser "assuming" the icon is square means here. Alternatively, the size format should allow specifying width and height. It's totally okay to say that if an icon is square then you can just give one dimension, but you should call out what happens if the icon is not.

**Comment by npm1** [comment]
I think generally MUST/SHOULD applies to user agent steps, not about guidance to developers. Since this is about a requirement to the developer, but perhaps we can make it clearer that the user agent must reserve a square space for the images, and may choose how to handle rectangular images (disregard/trim).
