### ISSUE TITLE
IdP has to check the referrer of RP not to give IdToken to unexpected RPs

### ISSUE THREAD

**Issue by manyhotcakes** [fedidcg/FedCM#325]
Hi, team.

From the aspect of IdP, we found that if any RP hosts the implementation of https://fedcm-rp-demo.glitch.me/ to another domain, they can receive the IdToken for https://fedcm-rp-demo.glitch.me/ from the IdP even though it's not hosted by the actual RP. 
(We found this 2 weeks ago and reported it to @agektmr )

I understand that the current implementation on https://fedcm-rp-demo.glitch.me/ has already solved this issue by checking the referrer of RP in IdP, but it's not written in the FedCM specifications.

I think it'd be the mandatory thing all IdPs using FedCM have to do. Do you have a plan to write it in the specs?

(BTW, the instruction of checking referrer was written in https://developer.chrome.com/blog/fedcm-origin-trial/ as "an important security information" just recently)

_Maybe this topic is related to https://github.com/fedidcg/FedCM/issues/114_

**Comment by npm1** [comment]
Yea we could add a non-normative note with developer guidance. The spec is mostly defining algorithms for the browsers but we can add some comment here if that would be helpful.

**Comment by kdenhartog** [comment]
This seems like a security issue that if it's not normatively defined. Otherwise it could be used as a vector to take tokens that can be replayed to the RP later. What's the reason for making this non-normative?

**Comment by lishiki** [comment]
There are two options to prevent this kind of vulnerability:
- IdP returns a RP's origin field as client metadata in addition. UA can compare origin and cancel the login flow.
- IdP checks the referrer when retrieving the id token. You can reject requests from different origin.

If anything, the former looks more secure because it can force IdPs implementation. The latter is left to IdPs.

Incidentally, my fake RP that just copied the demo RP was working until a few days ago. In other words, I was able to steal id token with just one click of a victim.
The demo IdP has now been fixed to validate the Referrer a few days ago, so it doesn't work now.
Fake RP(changed the design to distinguish them.): https://lishiki.github.io/fedcm-fake-rp/

**Comment by npm1** [comment]
> There are two options to prevent this kind of vulnerability:
> 
> * IdP returns a RP's origin field as client metadata in addition. UA can compare origin and cancel the login flow.

The referrer (RP) is already part of the ID token fetch. I don't think it makes sense for the user agent to then request the RP again and check against it, in case the IDP forgot to check....

> This seems like a security issue if it's not normatively defined. Otherwise it could be used as a vector to take tokens that can be replayed to the RP later. What's the reason for making this non-normative and more importantly what's the value in allowing an RP to be able to misrepresent itself?

Given that this is something that an IDP should do, it makes sense as non-normative guidance. The spec is normative only in regards to what the user agent must do. I'm not saying this should be considered optional for an IDP, I'm just saying this is not really within the scope of the spec to make sense as normative.

**Comment by kdenhartog** [comment]
> Given that this is something that an IDP should do, it makes sense as non-normative guidance. The spec is normative only in regards to what the user agent must do. I'm not saying this should be considered optional for an IDP, I'm just saying this is not really within the scope of the spec to make sense as normative.

Ok I get where you're coming from and I think I just keep ending up on a different approach because this scoping allows for trivial issues to appear in the implementation. Without considering the behavior of all 3 roles that have to be played in order to make this secure it seems like we'll keep running into this risk so would it make sense to expand the scope of this document (or define a separate document for RPs/IDPs) so that we can have more certainty around the effectiveness of the protocol as a whole?

**Comment by npm1** [comment]
Based on some internal discussion it sounds like I might be wrong and we can add this as normative text.
