### ISSUE TITLE
Support different encoding formats for the HTTP endpoints

### ISSUE THREAD

**Issue by samuelgoto** [fedidcg/FedCM#334]
The `accounts_endpoint` and `client_metadata_endpoint` currently send `x-www-form-urlencoded` to web servers. 
We hear from IdPs that some frameworks (e.g. Spring) default to produce/consume `applicaton/json` which would make it easier to integrate for them if we supported.

Not sure how to solve this, but a few initial ideas that occurred to me were (a) adding a configuration declaration in the `configURL` or (b) making an OPTIONS HTTP request before hand (seems overkill?).

On (a), this is what it could look like:

```json
{
   "accounts_endpoint": {
       "accepts": "application/json",
       "url": "/accounts.php",
    }
}
```

**Comment by cbiesinger** [comment]
Hmm before we add such complexity we should learn more how hard this is for such frameworks. How do they handle form submissions...?

**Comment by cbiesinger** [comment]
Based on https://stackoverflow.com/questions/47853462/how-to-properly-receive-urlencoded-form-body-with-spring it seems straightforward in spring to handle urlencoded formats, and since regular form submissions also use this format surely frameworks have to support it.

Producing JSON is not an issue because we already use JSON in the endpoint responses.

Since this has not come up again in the last two years, I recommend closing this.

(by the way, the client metadata endpoint does not use urlencoded, it uses GET)
