### ISSUE TITLE
Iframe-origin in the FedCM UX is sometimes not meaningful to users 

### ISSUE THREAD

**Issue by yi-gu** [fedidcg/FedCM#449]
Some websites delegate authentication to a cross-origin iframe that they own. e.g. ebay.com embeds ebaystatic.com where FedCM API is invoked from. Showing the iframe domain unnecessarily confuses users because they trust eBay (the RP) and are not familiar with ebaystatic.com (the domain). e.g. a user will likely be confused when they see the following UI while visiting ebay.com
<p align="center">
     <img width="467" src="https://github.com/yi-gu/fedcm-images/blob/main/iframe-ebay-3.png?raw=true"/>
</p>
Ideally, the user shouldn’t need to have to care about the relationship between ebaystatic.com and ebay.com so the mock below makes more sense to the user.
<p align="center">
     <img width="467" src="https://github.com/yi-gu/fedcm-images/blob/main/iframe-ebay-2.png?raw=true"/>
</p>
Omitting the iframe domain makes sense in this case but not so much in other use cases. e.g. travel.example embeds a third-party booking.example where FedCM API is invoked. When the user is signing into booking.example (where the token is issued to) with idp.example, they are not signing in to travel.example. Therefore the string “sign in to travel.example with idp.example” when omitting the iframe domain is incorrect and showing all 3 domains on the UI to provide users the complete information is better. 
<p align="center">
     <img width="467" src="https://github.com/yi-gu/fedcm-images/blob/main/iframe-idp.png?raw=true"/>
</p>
We should have a way to differentiate between the two use cases.

**Comment by yi-gu** [comment]
> **Note**
> Strings on the FedCM UI are not supposed to be standardized and different browsers may have different criteria on what has to be shown on the UI. This proposal does not intend to normalize the strings, rather, it proposes a way for browsers to differentiate between the two use cases mentioned in this issue and present meaningful UI to users accordingly if desired. Given that the issue may not apply to all browsers the proposal is optional to both developers and UAs.

For this proposal, let top frame origin be https://top-frame.example/, RP iframe origin be https://iframe.example and IDP origin be https://idp.example. top-frame.example embeds iframe.example with proper permissions policy that allows the iframe to call FedCM API.

# Matched clients
Any application that uses OAuth 2.0 must have authorization credentials i.e. a client ID which identifies the application to the IdP server. When a top frame has the same client ID as the iframe (RP) that calls FedCM API, the top frame is considered a matched client to the RP. In this case showing both the top frame domain and iframe domain can unnecessarily confuse users without gaining privacy/security benefits. Given that the top frame domain is the one that users see in the URL bar, omitting the iframe domain could lead to better UX.

Note that “client ID” is just one possible way to tell whether the top frame is a matched client to the RP iframe, IdPs may have other mechanisms to check it. e.g. same-site frames could also be a factor to some IdPs.

## How to use matched clients
The proposal is to use this as an indication for whether we should only show two domains (top frame and IdP) or show all three domains (top frame, iframe and IdP).
<p align="center">
     <img width="467" src="https://github.com/yi-gu/fedcm-images/blob/main/matched-clients.png?raw=true"/>
</p>

## How to determine matched clients
The browser currently sends the iframe origin as the `Origin` in the fetch to an IdP’s client metadata endpoint. The proposal is to include the top frame origin in the fetch, i.e. in the body of the GET request:
```
GET /client_metadata.php?client_id=1234&top_frame_origin=https://top-frame.example HTTP/1.1
Host: idp.example
Origin: https://iframe.example/
Accept: application/json
Sec-Fetch-Dest: webidentity
```
This would provide the IdP sufficient information to check if the top frame is a matched client. e.g. when an RP registered two different origins or domains for themselves, they should be issued the same client ID by the IdP if those domains are for the same RP. Then the IdP can look up the two origins to check if they belong to the same RP.

Then in the client metadata fetch response, the IDP would specify an optional boolean parameter `client_matches_top_frame_origin`:
```
{
  "privacy_policy_url": "https://rp.example/privacy_policy.html",
  "terms_of_service_url": "https://rp.example/terms_of_service.html",
  "client_matches_top_frame_origin": true  
}
```
And the browser can use `client_matches_top_frame_origin` to determine whether to show two domains or three domains. Note that if `client_matches_top_frame_origin` is not specified, the default value is false to err on the side of caution.

# Security and privacy considerations
Technically speaking this proposal provides a new way for an embedded iframe to learn the origin of the top frame. In particular, an iframe could call FedCM with their own fake IdP that receives both the iframe origin and the top frame origin. However, for a cross-origin iframe to call FedCM API, by design the top frame must allow it explicitly by specifying the permissions policy “identity-credentials-get”.

It is already possible today in some browsers for an iframe to learn the top frame’s origin via [ancestorOrigins](https://developer.mozilla.org/en-US/docs/Web/API/Location/ancestorOrigins). While Firefox has [concerns](https://bugzilla.mozilla.org/show_bug.cgi?id=1085214#c26) about `ancestorOrigins`, one key difference between this proposal and `ancestorOrigins` is the permissions policy requirement. i.e. by design, for the iframe to learn the top frame’s origin via FedCM, all the frames on the embedding chain must opt in (trust the embedded iframe) by specifying the permissions policy “identity-credentials-get”. This could make a difference according to this [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1085214#c4).

Another new entropy this proposal adds is that it technically provides a way for anyone to query the association between two origins with a specific client id using curl. e.g. https://foo.example/ registered themselves to an IdP with `client id: client_foo`. This information is public. Then someone can use curl to send a request to the client_metadata endpoint with that information plus `top_frame_origin=https://bar.example/`. The IdP would then let the requestor know whether bar.example is a matched client to foo.example. That being said, technically speaking the information which the requester can obtain should also be publicly available. In addition, this can be achieved without this proposal by sending two separate requests to the endpoint with the two origins and comparing the responses. 

From Chrome privacy’s perspective, we believe that showing less confusing UIs could help users to make more meaningful decisions when prompted to continue with FedCM.

Technically, the IdP can lie about the new boolean. However, omitting the iframe domain when it’s not supposed to could put the IdP at risk because it’s the iframe who receives the token with sensitive information. For legitimate IdPs this is definitely not in their interest. For bad acting IdPs, they have to collude with the top frame to explicitly use the permissions policy to use FedCM, but in case of collusion, the bad actor does not need to use an iframe at all.

# Interoperability and compatibility considerations
As noted in the beginning, this issue may not be browser-agnostic because it’s a string issue on the browser UI. For browsers who don’t have this issue, the proposal is completely optional and backwards compatible. For browsers who share the same issue, we believe that the proposal is designed in an interoperable manner.

# Considered alternatives
## Check matched client from the browser side
Instead of the browser sending both the top frame origin and iframe origin to the IdP, the IdP can return a list of origins that are “matched” in the client metadata fetch response. Then the browser can try matching the top frame origin from that list to see if it’s matched. However, there are some drawbacks of this alternative:
- IdP needs to expose information that is otherwise unavailable to all requesters. Hashing the returned origins may help to some extent, but it may still raise a red flag for IdPs given the sensitivity of the information.
- IdP may have different criteria to determine “matched clients”. e.g. two domains that are cross-origin but same-site (https://foo.rp.example and https://bar.rp.example) could be considered as “matched clients” to each other. Asking IdP to return a full list of such origins is suboptimal.
## Using different permissions policies
We could introduce two different permissions policies for FedCM in cross-origin iframes: “identity-credentials-get-include-iframe-domain” and “identity-credentials-get-omit-iframe-domain” to give the control to the top frame. However there are some drawbacks:
- If a top frame chooses to omit the iframe domain when it’s not supposed to, users would make decisions based on incomplete information and IdP may expose the token to the iframe which could be a bad actor that’s different from the top frame.
- API confusion. This puts an extra burden on the top frame to use permissions policy properly.
- Typically how to build browser UI is not standardized. Adding a new API to control the string is undesirable.

**Comment by yi-gu** [comment]
@martinthomson @cboozar @bvandersloot-mozilla 
From Chrome's perspective, we do want to differentiate the two use cases to prompt proper UI to users. Not sure whether Firefox has the same confusing UI issue when FedCM is used in a cross-origin iframe.
 - If so, for this proposal, is our understanding of Firefox's position on `ancestorOrigins` correct? In particular, is the permissions policy requirement sufficient to reveal the top frame origin (just top frame, not the other nested iframes if any) to the iframe who uses FedCM API?
 - if not, do you think this proposal can be spec'd in a reasonable manner?

**Comment by philsmart** [comment]
To me, it seems confusing to say, 'the clientID matches not only the Origin header...', the client_id can be any string, not necessarily related to an origin. From the later text, it seems client_id is used to locate registered origins related to a client (something equivalent to what Google stores about OAuth2 clients, namely; 'Authorised JavaScript origins'). Maybe that could be clarified in the text (if I am not wrong about it). 

I would not imagine every OAuth2 (or OIDC etc) authorization server would store an equivalent to 'Authorised JavaScript origins'. I do not think it is part of any OAuth2/OIDC registration spec? This would mean this would need to be specified as a FedCM registration extension for it to be widely used.

**Comment by yi-gu** [comment]
> To me, it seems confusing to say, 'the clientID matches not only the Origin header...', the client_id can be any string, not necessarily related to an origin. 

Totally agree. We deliberately chose the phrase "**client** matches top" just to give IdPs more flexibility to determine "match". It does not necessarily get narrowed down to using "client ID". e.g. client ID may not needed at all in the process because IdP can look up the two origins and determine if the browser can skip showing one of them.

**Comment by npm1** [comment]
On the call ([notes](https://docs.google.com/document/d/1O7Rn8Aj4rsYWohdEP61lnGdgkai0xTZFQgm7XEA0RBM/edit#)), a suggestion was made to consider using First Party Sets (FPS) to solve this problem. That is, the user agent would check whether the iframe and the top-level embedder are members of the same FPS to determine whether to show two or three domains in the UI. The benefit of this would be that it would not require introducing a new API. With FPS now [shipping](https://groups.google.com/a/chromium.org/g/blink-dev/c/7_6JDIfE1as/m/t02qTcCYAAAJ) in Chrome, Chrome could use FPS as the solution. We took the AI to ask FPS folks what they think and the consensus seems to be leaning towards not using FPS for the following reasons:

* It would mean integrating FedCM with a controversial API, in particular one that [Firefox](https://github.com/mozilla/standards-positions/issues/350) and [Webkit](https://github.com/WebKit/standards-positions/issues/93) aren’t favorable of
* The origins would need to publicly share their relationship as part of a FPS, which some RPs might be concerned about
* Requires non trivial work from RPs compared to the proposed solution that puts the work onto IDPS

Tagging @johannhof @krgovind in case they want to share their thoughts from the FPS side!

**Comment by krgovind** [comment]
Thanks for summarizing, @npm1! I agree with your assessment. 

Interoperability should definitely be a consideration here. The only other proposed integration of FPS on the platform today is with the `requestStorageAccess` and `requestStorageAccessFor` APIs, and browsers that don't support FPS have their own handling of those API calls. For example, Firefox currently auto-grants the first five invocations of `requestStorageAccess` for a given 3p site, and prompts users beyond that. Safari always prompts. (`requestStorageAccessFor` is a new proposal, and still under discussion).

Since it appears that RPs already register their list of related sites with their trusted IDPs; I believe the purpose that FPS serves for the cross-site cookie access use-case (i.e. provide a platform mechanism for site authors to declare collections of related sites) is already superseded by that existing mechanism. It makes sense to leverage that.

**Comment by martinthomson** [comment]
(This all assumes cross-site cookie blocking or isolation.)

I'm happy with the conclusion about FPS, though I had a shorter path to reach it :)

I think that the model this should use is the one we adopted for permissions policy, which this API already uses.  That is, if a top-level context wants to delegate permission, then it can do so.  But the effect of that is that they are responsible for the effects of that.  So maybe this is really api.mallacoota.example.net asking rather than example.com, but the user doesn't need to care about that distinction.  The information is transferring to the example.com partition of browser state and that is what really matters, not who they contract with to manage a given component of their site.

The challenge then is the accountability at the IdP end.  The IdP will report access from some obscure site, which isn't ideal.  So, we can tell them the origin from the top-level context.  Then they can report that.  We can make the automated availability of that datum a non-negotiable part of the contract when the top-level site allows the use of this API in a given frame.  There is no privacy risk there because sites can already arrange to make that information available if they chose to.  

The proposed design pushes that work back on sites, which is annoying for them and provides no privacy advantage.  So my suggestion is that we decorate these fetches as follows (precise spelling TBN):

```
Origin: api.mallacoota.example.net
Top-Origin: example.com
```

You might notice that this has more general applicability.  We don't do this now, so we probably shouldn't start without sites asking us to, but we can definitely do that here.

(This idea of matched clients using client ID makes no sense to me.  That two sites might have the same client ID with a given IdP is not information that a browser can - or should - be making decisions based on.)

**Comment by npm1** [comment]
Thanks for the feedback, @martinthomson! I do agree that it is a bit awkward for the user agent to trust the IDP with the task of attesting that two origins are the same client. That said, having a Permissions Policy be the solution for this is not something we would be supportive of because it is possible for an attacker to grant itself permissions via the [HTML injection attack](https://shhnjk.blogspot.com/2018/09/what-permission-delegation-changes-in.html). This was one of our motivations for this feature, as well as for displaying three origins the default instead of two.

That said, @rbyers suggested that perhaps we can just change the solution slightly so that JavaScript must be called in order for the embedder to grant permission. That is, we'd have a JS call that the embedder needs to call to grant its iframe permission to use FedCM. This could be in addition to or in replacement of the existing API:
* In addition to: the JS call lets the iframe's FedCM prompt display only two origins.
* In replacement of: instead of using Permissions Policy as a framework to grant access, we rely solely on this API call, and the prompt displays only two origins.

What do you think? We're also waiting for @yi-gu to come back from vacation as he's been driving this API and will have thoughts :)

**Comment by martinthomson** [comment]
HTML injection is why we have CSP.  I'm not convinced that that motivates poor UX.

This permission delegation problem is real, but I don't think that it is our business to come up with a solution to it here.

**Comment by martinthomson** [comment]
Option 5: open an issue on the permissions policy repository and solve the problem for everyone and for every feature for which this might be is a problem.  A CSP directive is my preferred approach.

**Comment by RByers** [comment]
Thanks @martinthomson, FWIW I agree 100% with your perspective here. Yi has looped me into the discussion with our security teams and we'll follow up here once we have a conclusion from that.
