### ISSUE TITLE
The generation and management of IDs created through these flows should allow other wallets to act as the Identity Agent

### ISSUE THREAD

**Issue by timcappalli** [fedidcg/FedCM#48]
The browser should provide extensible points for other wallet applications to act as the user’s Identity Agent and handle all flows related to IDs and data disclosure.

**Comment by samuelgoto** [comment]
Sure, I think that seems uncontroversial. 

It is not clear to me whether that should be a "web platform feature" (i.e. an API) or a "browser feature" (i.e. something that you set up in your browser settings).

If it is the latter (a browser feature), then each browser can provide their own integration with "identity agents" (analogous to de-coupling password managers).

If it is the former (a web platform feature), that's probably more involved, but doesn't seem in antagonistic to the current design.

**Comment by samuelgoto** [comment]
In as much as I think this is something that I remain interested in (OS / App integrations), we haven't heard from any developer since this was filed that this what they needed and was holding them back using FedCM.

I'm going to close this until there is evidence of developer demand and becomes actionable, feel free to reopen if you feel know any developer that needs this.
