### ISSUE TITLE
External revocation after password change or security breach

### ISSUE THREAD

**Issue by jameshartig** [fedidcg/FedCM#73]
Upon password changes or security breaches IDPs typically will revoke all authenticated "sessions" and force the user to reauthenticate. One method of solving this would be to add another "revalidate" field after which the browser would have to ask the IDP if the previous token is still valid. However that would allow the IDP to do some tracking of which RPs are being used and when. Another solution is just making the expiration short, like an hour, but that might be annoying to users if they have to reauthenticate frequently.

**Comment by majido** [comment]
OAuth have  a recommended ["expires_in" field](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2) that can be associated with the token response. I think this matches your suggestion for "revalidate" field. The IDP being in charge of that value means that they can use it to trade-off  between user convenience (longer expiry) and  security posture (shorter expiry). 


If I understand correctly, the tracking vector you are concerned with is that a nefarious idp would set a very short expiry time to force the user to "re-auth" every time and thus track their access to *this specific RP* over time. This is interesting specially if the user agent is less restrictive on subsequent re-auth making this type of tracking hard to detect by user. A possible prevention vector on this is to mandate a minimum expiry time (e.g., 8 hours). In this light, I don't really understand how making the expiration shorter would mitigate this since I think the mitigation lies in the opposite.

Note that if the IdP has any script running in the RP page (even as a 3P), they have a much easier tracking vector after the first id_token exchange given they can already identify the user on RP site.

**Comment by cbiesinger** [comment]
Tokens are opaque to the user agent and are not stored. I don't think there's anything the browser can or should do for this situation. https://fedidcg.github.io/FedCM/#dictdef-identityprovidertoken

Feel free to reopen if you think there is something actionable here.
